name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Run tests
        run: |
          mkdir -p /home/runner/.config/dugit
          echo "{ \"accessToken\": \"${{ secrets.DUGIT_TOKEN }}\" }" >> /home/runner/.config/dugit/config.json
          npm run test
